Power Connection Receiver
koreader/android-luajit-launcher pull request #294
Opened 2021-03-06 16:53 UTC by zwim

This adds a receiver for the power connection. -> Will be used for the upcoming power connections events.

2021-03-06 16:57 UTC, Frenzie commented on app/src/main/java/org/koreader/launcher/PowerConnection.kt
> +    var isPowerConnected = 666
Wouldn't it make more sense to initialize it to 0?

2021-03-06 17:18 UTC, zwim commented on app/src/main/java/org/koreader/launcher/PowerConnection.kt
> +    var isPowerConnected = 666
The evil number just shows, that the var is not initialized - as we don't know the state here.
A call to `getBatteryState` will initialize the the value. 
Maybe it will be better to call `getBatteryState` here (instead of 666).

2021-03-06 17:52 UTC, NiLuJe commented on app/src/main/java/org/koreader/launcher/PowerConnection.kt
> +    var isPowerConnected = 666
`-1`?

2021-03-07 15:09 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +    override fun getBatteryState(isPercent: Boolean): Int {
Please don't!!

getBatteryState is a private function for a good reason. It is already exposed to lua in both variants: percent and isCharging. Leave it that way.

2021-03-07 15:11 UTC, pazos commented on app/src/main/java/org/koreader/launcher/PowerConnection.kt
> +				// replace this by a better method to send a keyevent to self (so ALooper_pollAll wakes up)
THAT! Using `su` in a general purpose class is a big **nope**.

2021-03-07 15:12 UTC, pazos commented on app/src/main/java/org/koreader/launcher/interfaces/JNILuaInterface.kt
> +    fun getBatteryState(isPercent: Boolean): Int
^^

Already exposed as `getBatteryLevel` and `isCharging`

2021-03-07 15:14 UTC, pazos commented on assets/android.lua
> +    android.powerConnectionEvent = function()
I don't understand why you need that. Isn't that polling? How is this different that calling `isCharging`?

2021-03-07 15:21 UTC, pazos requested changes
If you manage to gen a fake key event using public SDK/NDK methods then I think it should be ok. In that case:

1. Get rid of the PowerConnection class and make it an inner class of MainActivity (it's always called from there and will be the same in all devices, there's no need for an extra file)
2. Get rid of the extra android functions since you won't need them. The key event will be delivered to the frontend and can be handled there
3. On the same vein, since you're registering the broadcast receiver in onCreate you should keep the var `isPowerConnected` or `lastPowerConnectedState` as a MainActivity class var. The same for the function `connectionEvent` since now it compares values that are available on MainActivity.

2021-03-07 16:04 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +    override fun getBatteryState(isPercent: Boolean): Int {
With this PR `getBatteryState()` is only called from `getBatteryLevel()`.
`isCharging()` uses the stored `isPowerConnected` property, which is way faster than `getBatteryLevel()`.

 So no problem in keeping that private.

2021-03-07 16:06 UTC, zwim commented on app/src/main/java/org/koreader/launcher/PowerConnection.kt
> +				// replace this by a better method to send a keyevent to self (so ALooper_pollAll wakes up)
I totally agree that this is the point to solve in this draft PR. That's why the comment is there :))

2021-03-08 19:17 UTC, zwim commented
@pazos : My idea would be:
1.) Create a fifo/pipe.
2.) When MainActivity/PowerConnection/onReceive receives a PowerConnection-event then the new state (on/off) is written to the fifo.
3.) In android-main.c append a `ALooper_addfd` on that fifo,  so that `ALooper_pollAll` finishes.

Then the new connection state could be used in the LUA-space after ALooper_pollAll.

What do you think about this approach?

2021-03-08 19:29 UTC, NiLuJe commented
I don't know how this affects Android, but be aware that polling a RW pipe has some *very* funky corner-cases: https://stackoverflow.com/a/17384067

(I had to deal with the weirdness in [FBInk](https://github.com/NiLuJe/FBInk/blob/e685897a1bb4e37903e4896e518368d1f220846d/fbink_cmd.c#L2064-L2069)).

2021-03-11 20:37 UTC, zwim commented
Now we have a FIFO (`alooper.fifo`) for communication from Kotlin to Lua. The data transferred is rudimentary for now. Namely this is just a flag, that something notable happened on Android. What this was has to be checked from Lua. Up to now, only one event (Charging/NotCharging) is signalled with this, so there is no "dispatcher" to detect anything else :))

2021-03-11 21:24 UTC, NiLuJe commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +val ALOOPER_FIFO = "/data/data/org.koreader.launcher/files/alooper.fifo"
This probably won't work on newer APIs with weird-ass storage containers, will it?

2021-03-11 21:26 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    } else
Braces or no braces (I don't know the house style for the rest of the file), but only half or the braces is super-weird ;).

2021-03-11 21:26 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    } else
(I'm personally rather fond of enforcing braces, always, everywhere, even for single-lines. But that's me.)

2021-03-14 10:38 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +val ALOOPER_FIFO = "/data/data/org.koreader.launcher/files/alooper.fifo"
`getFilesDir()` is used from MainActivity.kt and `activity->internalDataPath` on the native_app_glue.c

2021-03-14 17:06 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    strcat(fifo_file, FIFO_NAME);
```suggestion
char fifo_file[strlen(fifo_path) + strlen(FIFO_NAME) + 2] = { 0 };
snprintf(fifo_file, sizeof(fifo_file) - 1U, "%s/%s", fifo_path, FIFO_NAME);
```

2021-03-14 17:10 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    int result = read(fd, &c, sizeof(c));
```suggestion
    ssize_t result = read(fd, &c, sizeof(c));
```

2021-03-14 17:11 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    int fifo_fd = open(fifo_file, O_RDWR | O_CLOEXEC);
Shouldn't this be `O_NONBLOCK`, too?

2021-03-14 17:36 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    strcat(fifo_file, FIFO_NAME);
`{ 0 }` Initializing cannot be done with variable sized arrays at least in C.

2021-03-14 17:41 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    strcat(fifo_file, FIFO_NAME);
Whoops, indeed those are strlen calls, not sizeof calls ;p.

Uglier option, then:
```C
char fifo_file[strlen(fifo_path) + strlen(FIFO_NAME) + 2U];
snprintf(fifo_file, sizeof(fifo_file) - 1U, "%s/%s", fifo_path, FIFO_NAME);
fifo_file[sizeof(fifo_file) - 1U] = '\0';
```

2021-03-14 17:41 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    strcat(fifo_file, FIFO_NAME);
(Or just use `PATH_MAX`).

2021-03-14 17:48 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    strcat(fifo_file, FIFO_NAME);
Shouldn't that be `sizeof(fifo_file)` without the `-1U`?

2021-03-14 17:51 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    int fifo_fd = open(fifo_file, O_RDWR | O_CLOEXEC);
I have tested this on a phone and a Tolino. 
With `O_RDWR`  `O_NONBLOCK` is not necessary.
Only with `O_RDONLY` we would need nonblock.

2021-03-14 17:54 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    strcat(fifo_file, FIFO_NAME);
The last slot of an n-bytes array is at n-1 ;).

(`sizeof` does just what it says on the tin. You were perhaps thinking of `strlen`, which doesn't count NUL bytes. But since the goal here is to ensure NUL termination, we can't rely on strlen ;)).

2021-03-14 17:58 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    strcat(fifo_file, FIFO_NAME);
Yep, you were talking about the `snprintf` ;).

In this specific instance it's harmless, but it'll made static analyzers scream at you nonetheless ;).

2021-03-14 18:00 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    int fifo_fd = open(fifo_file, O_RDWR | O_CLOEXEC);
I'm not quite sure what the R/W status would change, but since it's only used in a polling loop, it just makes more sense to me as NONBLOCK (again, mostly harmless in practice, until the day something possibly goes wrong ^^).

2021-03-14 18:40 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = ALooper_prepare(ALOOPER_PREPARE_ALLOW_NON_CALLBACKS);
Please don't change names without a good reason. It makes harder to understand the changes. `looper` is a good name for an ALooper instance. There's no need to change it to `native_glue_looper`

2021-03-14 18:41 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +import android.content.BroadcastReceiver
please sort the imports, like the rest of the file

2021-03-14 18:44 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +int fifoCallback(int fd, int events, void *data)
Please add a multiline comment on this one, because the rest of the file is mostly vanilla from Android NDK sources. It can be useful if we need to backport newer changes to our tree (last update on android native glue was made with NDKr22)

2021-03-14 18:46 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +// ToDO: How can I retrieve the path to the cache directory from here (native_app_glue)?
old comment?

2021-03-14 18:51 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    strcat(fifo_file, FIFO_NAME);
I think it is like the following:
string1="xyz", string2="abcd"; strlen1=3 strlen2=4.
If we concat "xyz/abcd" we would need an array with 3+1+4+1 =9bytes (strlen1+strlen2+2).
When calling `strnprintf` we give the size 9, as the man page say, that size bytes are written (including the terminating NUL).
`fifo_file[sizeof(fifo_file) - 1U] = '\0';` is not necessary then, but does no harm.
Am I wrong?

2021-03-14 18:54 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = ALooper_prepare(ALOOPER_PREPARE_ALLOW_NON_CALLBACKS);
We can leave the name `looper`, but then we need an additional global variable `native_glue_looper=looper` in the `ALooper_addFd` to wake the thing.

2021-03-14 18:54 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +import android.content.BroadcastReceiver
OK

2021-03-14 18:55 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +int fifoCallback(int fd, int events, void *data)
OK

2021-03-14 19:00 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +// ToDO: How can I retrieve the path to the cache directory from here (native_app_glue)?
Yepp.

2021-03-14 19:07 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = ALooper_prepare(ALOOPER_PREPARE_ALLOW_NON_CALLBACKS);
yup, new stuff is ok. For existing stuff please keep the names. The files are mostly vanilla from https://android.googlesource.com/platform/development/+/4948c163663ecc343c97e4c2a2139234f1d3273f/ndk/sources/android/native_app_glue

2021-03-14 19:30 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        fun feed_alooper_fifo(state: Int) {
very interesting approach :+1: 

IIRC this can be used to execute arbitrary lua chunks based on android events, isn't it?

In that case I would propose to move the code outside the broadcast receiver class.  For instance we keep some values that are the same for the entire life of the app in https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/MainApp.kt and just use them with `MainApp.whatever`. You can put there the path to `"alooper.fifo" and just have a private function in MainActivity that post messages to it. Not sure if you can do the initialization in MainApp too. If that's possible it would be amazing

2021-03-14 19:35 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +                    isPowerConnected = 1
since we can feed other "states" through the fifo it would be nice to have a couple of constants instead of raw numbers. See https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/Device.kt#L60-L77, for example. You can name them as you wish, and being very verbose is suggested. (Something like `ALOOPER_FIFO_MSG_CONNECTED` is fine)

2021-03-14 19:35 UTC, pazos commented on assets/android.lua
> +// for alooper.fifo event
Is this still relevant?

2021-03-14 19:41 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        return powerConnection.isPowerConnected != 0
This one was fine as is. Keep in mind there're some pretty borked android devices out there. A function that returns if the device is charging should actually check if it is changing right now and not returing the last state registered.

The medium overhead per JNI call is at most a ms. I think we can afford it :)

2021-03-14 19:50 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    strcat(fifo_file, FIFO_NAME);
Yup, exactly ;).

2021-03-15 15:32 UTC, zwim commented on assets/android.lua
> +// for alooper.fifo event
no.

2021-03-15 15:32 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        return powerConnection.isPowerConnected != 0
Ok.

2021-03-15 15:39 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        fun feed_alooper_fifo(state: Int) {
I am afraid, it's not that easy. The only thing I can feed through the fifo is `ALOOPER_POLL_WAKE` as result of the `ALooper_addFD` callback.
If I delete the `ALooper_wake` from the callback and try to put some values to the `*data` pointer, I don't get any data in lua. Well not quite right. I get the data continuously flooding after a 40 secs or so and KOReader freezes.
With the `ALooper_wake` I get an immediate result.

So we could use the fifo for signalling that there is something and then maybe ask some data from java-land, what the "event" was but not the `android_poll_source` struct.

2021-03-15 15:40 UTC, zwim commented
In the next time (until Easter) I won't have time to work on that. So if someone would like to overtake the work, fell free to do so.

2021-03-15 18:20 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        fun feed_alooper_fifo(state: Int) {
maybe store the code that caused the wake in a var and use a new function to check that var in base (instead of asumming is a power event)?

We already do something like that to check the path of the file returned from SAF: [lastImportedPath](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/MainActivity.kt#L34-L35). It is nullable and, when not null, provides a string with a path to a file. The function `getLastImportedPath` returns its value and resets it to null.

Maybe you can do the same with an `Int?`, that you feed with a non null value in the broadcast receiver. In the poll loop when Alooper wakes you check its code and act accordly

What do you think? :)

It would be a pitty to have such a nice feature constrained to a very minor/specific event :)

2021-03-15 20:45 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        fun feed_alooper_fifo(state: Int) {
> What do you think? :)

That would have been my idea: First we need to define the data-structure which is written to the fifo (e.g. 2x16Bit: 65356keys with 65356values each; this has to be decided by YOU before we start implementing it). The Alooper_addFd callback reads these four bytes and stores them. When an ALOOPER_POLL_WAKE occurs, we read the stored data with a function in base (android-input.lua) and create a misc event (which we can handle with handeMiscEv in android/device.lua throwing some events) or do whatever we want directly in base (call some base function ...).

Stumbling blocks are: reading from the fifo:
1: I didn't get O_NONBLOCK to work reliably (maybe my fault). Have to dig into that (no time now :(  ).
2 : With more than one byte of data we have to synchronize the communication. Otherwise we might get freezes if a byte gets lost. -> Could be done by not allowing a zero byte in the data (zero-byte==wrong data) -> needs quite some test (and time :( ).
3: Two or more senders writing at the same time to the fifo (I know, fifo atomic blablabla), has to be tested before the feature is getting cool. (Maybe some sort of checksum will be needed?)
   
Benefits: Every part of KOReader (including the java and native parts) can send a huge number of different messages to lua-land. In lua-land for each message a helper can be called to retrieve the associated data.

> 
> It would be a pitty to have such a nice feature constrained to a very minor/specific event :)

Yes, the idea is expandable and should be pursued further, but I just don't have the time to do (and test it) now.
In the Easter holidays my time budget is better.

2021-03-15 20:47 UTC, pazos commented
> In the next time (until Easter) I won't have time to work on that. So if someone would like to overtake the work, fell free to do so.

We can wait a few weeks without doubt :) Very good job up to now

2021-03-15 21:02 UTC, zwim commented
> We can wait a few weeks without doubt :) Very good job up to now

I had good and tolerant teachers :))

2021-03-15 21:03 UTC, NiLuJe commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        fun feed_alooper_fifo(state: Int) {
About 3.: Yeah, on Linux, a FIFO should ensure atomicitiy, boundaries and order are respected up to PIPE_BUF (4K).

2021-03-15 21:05 UTC, NiLuJe commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        fun feed_alooper_fifo(state: Int) {
And about 1.: What kind of issues did you encounter, in practice?

(Re: https://github.com/koreader/android-luajit-launcher/pull/294#issuecomment-793013837 ;)).

2021-03-15 21:10 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        fun feed_alooper_fifo(state: Int) {
good, so 2+3 wont need so mcch tests.

2021-03-15 21:14 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        fun feed_alooper_fifo(state: Int) {
To 1: I got the same value over and over again, flooding. -> This means, that the addFd callback is called continuously, isnt it.

2021-03-16 01:44 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        fun feed_alooper_fifo(state: Int) {
We don't need fancy stuff passed using the fifo. Just use the fifo to tell the main thread (where LuaJIT runs and controls the loop) that there's a pending message and get that message using the new call. Something like this in base should work:

```lua
elseif poll_state == C.ALOOPER_POLL_WAKE then
    local event = android.getEvent()
    if event and event == C.EVENT_POWER_CONNECTION then
        -- stuff here to check that usercase
    end
end
```

the getEvent function (use a name you like) should return nil if the wake event is unexpected or a number described in a enum in `assets/android.lua`

You can also repurpose the event name to tell to the frontend. So, instead of `commandHandler(C.MSC_CHARGE, 1)` you'll use `commandHandler(C.EVENT_POWER_CONNECTION , 1)`

Again, names are mine and can be changed. But the general idea is:

1. Events that need to execute lua chunks use a general purpose function that stores an integer in a var somewhere in kotlin and send the same bit of info using the fifo to trigger Alooper_wake
2. The poll loop then checks that specific value (once per Alooper_wake) and send the message to the frontend accordly.

2021-03-16 02:25 UTC, NiLuJe commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        fun feed_alooper_fifo(state: Int) {
> To 1: I got the same value over and over again, flooding. -> This means, that the addFd callback is called continuously, isnt it.

That smells like one the many FIFO corner-cases, yeah (e.g., POLLIN never cleared or POLLHUP permanently set or something). I'd need to know how the Android stuff wraps `poll` to tell what's really happening, though ;).

Then again, if the actual `read` call returned content every time, maybe more complex than that... :/

2021-03-17 18:49 UTC, zwim commented
The following commits seem to work. But due to my restricted time resources they are not tested thoroughly.  I will do that in a few days.

2021-03-18 15:38 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainApp.kt
> +            if (!this::context.isInitialized) {
Not sure why are you using kotlin constructs for these kind of lateinit vars.

They aren't needed at all. If you need a context and can't get one here just move the function to MainActivity. In the same vein the FileWriter should be local in the function. Two or more broadcast receivers can write to the file "at the same time"

But, for the specific usage of the context you shouldn't have problems. (both the app and activity classes  inherit from a context)

See **https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/MainApp.kt#L26**

you don't need to use `context.getFilesDir()` Whenever possible prefer the more idiomatic `filesDir`

Assuming the same name for an example, but I think `postMessage` makes more sense than `feed_alooper_fifo`. The former shows intention and the later is a bit too techical and exposes implementation details

```kotlin
// Function in MainApp or MainActivity
fun feed_alooper_fifo(state: Int) {
    try {
        val writer = FileWriter(MainApp.fifo_path, true)
        val fifo_bytes = CharArray(4)
        fifo_bytes[0] = (state and 0xFF).toChar()
        fifo_bytes[1] = ((state ushr 8) and 0xFF).toChar()
        fifo_bytes[2] = ((state ushr 16) and 0xFF).toChar()
        fifo_bytes[3] = ((state ushr 24) and 0xFF).toChar()
        writer_write(fifo_bytes, 0, 4)
        writer.flush()
    } catch (e: Exception) {
        // whatever error msg
    }
}
```
}

2021-03-18 15:44 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainApp.kt
> +            if (!this::context.isInitialized) {
The bit of info I suggested for `MainApp` was

```diff
diff --git a/app/src/main/java/org/koreader/launcher/MainApp.kt b/app/src/main/java/org/koreader/launcher/MainApp.kt
index 823434d..7a65255 100644
--- a/app/src/main/java/org/koreader/launcher/MainApp.kt
+++ b/app/src/main/java/org/koreader/launcher/MainApp.kt
@@ -7,12 +7,16 @@ import android.content.pm.PackageManager
 import android.os.Environment
 import android.os.StrictMode

+import java.io.File
+
 class MainApp : android.app.Application() {
     companion object {
         private val runtime = android.os.Build.VERSION.SDK_INT

         lateinit var info: String
             private set
+        lateinit var fifo_path: String
+            private set
         lateinit var storage_path: String
             private set
         lateinit var platform_type: String
@@ -40,6 +44,10 @@ class MainApp : android.app.Application() {

         @Suppress("DEPRECATION")
         storage_path = Environment.getExternalStorageDirectory().absolutePath
+
+        /* */
+
+        fifo_path = File(filesDir, "alooper.fifo").path
         platform_type = if (pm.hasSystemFeature("org.chromium.arc.device_management")) {
             "chrome"
         } else if ((runtime >= 21) && pm.hasSystemFeature(PackageManager.FEATURE_LEANBACK)) {
```

Sorry for the confussion :)

2021-03-18 16:27 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainApp.kt
> +            if (!this::context.isInitialized) {
Thanks for the help. The code is much cleaner now.

2021-03-18 16:44 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainApp.kt
> +            if (!this::context.isInitialized) {
But it has to be tested yet.

2021-03-20 01:02 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +    inner class PowerConnection : BroadcastReceiver() {
We can use the same receiver to get all kind of system events. Most of them useless, of couse. The entire list as of API30 is https://developer.android.com/about/versions/11/reference/broadcast-intents-30

So I would suggest a more generic `Receiver` as the name of the class and `receiver` as the name of the object. Maybe `EventReceiver` and `event` ?

2021-03-20 01:09 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +                }
Kotlin needs an `else` branch when you use `when`.
Docs are https://kotlinlang.org/docs/control-flow.html#when-expression and seems a good habit to include an else branch even if is not strictly neccesary.

2021-03-20 01:10 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +        powerConnection = PowerConnection()
^^

2021-03-20 01:11 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +
unrelated change

2021-03-20 01:18 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainApp.kt
> +
I'm not sure where to put this chunk of code but very much not here :)

The rest of constants are placed in a companion object within the class. See, for example, https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/Device.kt#L60 or https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/MainActivity.kt#L70

2021-03-20 01:21 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
?

Please use `looper` everywhere.

2021-03-22 13:36 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
I need the `native_glue_looper` as a global variable for the `ALooper_wake` in the callback.

2021-03-22 13:38 UTC, zwim commented
From my side this PR would be ready. I have tested it on two Tolinos and my mobile.

2021-03-22 17:39 UTC, NiLuJe commented on app/src/main/java/org/koreader/launcher/MainApp.kt
> +                writer.write(fifo_bytes, 0, 4)
Stupid question: why the gymnastics here? this is not crossing a network boundary, what's wrong with writing an int on this side and reading an int on the other?

2021-03-22 18:37 UTC, pazos commented on app/src/main/java/org/koreader/launcher/Device.kt
> +        // These are the messages going over the fifo to the native glue.
Device is a good place (as MainActivity). If you go this route then make the constants private and use them in the same file. Both the broadcast receiver and the postMessages function should be placed here. (You can instantiate the broadcast receiver and the filter on the class constructor `init`.

2021-03-22 18:38 UTC, pazos commented on app/src/main/java/org/koreader/launcher/Device.kt
> +        // The defines here should correspond to the ones in android.lua
The comment is generic for the rest of the constants here. All of them need to be placed in `android.lua`

2021-03-22 18:39 UTC, pazos commented on app/src/main/java/org/koreader/launcher/Device.kt
> +        val ALOOPER_FIFO_POWER_CONNECTED = 100
A sugestion that hides implementation details is 

```kotlin
private const val EVENT_POWER_CONNECTED = 100
```

2021-03-22 19:56 UTC, zwim commented on app/src/main/java/org/koreader/launcher/MainApp.kt
> +                writer.write(fifo_bytes, 0, 4)
I use this, because the fileWriter doesn't have a method to write a 32bit int.

2021-03-22 20:43 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
Am I to stupid? 
The callback is called directly from `ALooper_pollAll()` and the parameters are (int filedescriptor, int events, void *data). How can I pass an additional parameter to the callback?
Or do you mean to fill the `message_to_lua` buffer with a reference to `looper` and then use a static variable within the callback to hold the reference for consecutive calls? That wouldn't be much clearer, wouldn't it?

2021-03-22 20:43 UTC, pazos commented on app/src/main/java/org/koreader/launcher/Device.kt
> +        activity.getApplicationContext().registerReceiver(event, filter)
nit: whenever possible use kotlin getters. In this case `activity.applicationContext` instead of `activity.getApplicationContext()`

2021-03-22 20:43 UTC, pazos commented on app/src/main/java/org/koreader/launcher/Device.kt
> +    fun postMessages(state: Int) {
nit: private

2021-03-22 20:49 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +int fifoCallback(int fd, int events, void *data)
`int fifoCallback(int fd, int events, void *data, ALooper &looper)` should work the same and avoids to modify the file more than necessary.

2021-03-22 20:50 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> -
nit: unrelated change

2021-03-22 20:52 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +        close(fifo_fd);
question: Do you want to remove the file here or shall we keep the file created from one execution to the next one?

2021-03-22 20:56 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +            LOGD("%s: FIFO \"%s\" already exists", TAG, fifo_file);
Actually we can use `LOGW`  or `LOGV` macros if they make more sense.  For example I wouldn't mind to have these logged on release builds as verbose messages. The macro is already used elsewhere, see https://github.com/koreader/android-luajit-launcher/blob/master/jni/android-main.c#L42

2021-03-22 20:57 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +        close(fifo_fd);
I would prefer to leave the file. Less disk accesses are better.

2021-03-22 20:57 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +            LOGD("%s: FIFO \"%s\" already exists", TAG, fifo_file);
OK

2021-03-22 21:00 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> -
OK

2021-03-22 21:07 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
I didn't know.

You already have a pointer to a ALooper. Why don't use it directly? Can't you use its memory address with `ALooper_wake(&looper)`?

2021-03-22 21:32 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
Hmmm. The callback gets called from ALooper_pollAll. The bad thing is, that the callback only gets those three parameters (and nothing more, we are on C here, aren't we?). So the callback has no clue about the looper structure/address or whatever. 
So my clumsy/smart (?) solution is the global variable `native_glue_looper`.

Sorry can't test more now, as I am fighting with git. I have done an update of `base` (wanted to try the awesome mathml things in crengine) and now I get the error:
`cre.cpp:504:20: error: 'PROP_FALLBACK_FONT_FACE' was not declared in this scope`

2021-03-22 21:40 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
(try a clean rebuild (e.g., make dist-clean).

2021-03-22 21:45 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
I have allrdy done a kodev clean android and after that a kodev build android. Did not help.

Thank you.

2021-03-22 21:54 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
Okay, read the context, and I'd tend to agree with @pazos.

One way i can think of to handle that: Use a struc,t allocate it on the stack, pass a pointer to *that* to the callback, and free it when the message has been consumed (in the callback?).

```
typedef struct {
    ALooper * looper;
    unsigned char msg[MESSAGE_SIZE];
} FifoCtx;

...

FifoCtx msg = calloc(1, sizeof(FifoCtx);
msg.looper = looper;

...

FifoCtx* msg = data;

...

```

Sidebar: What's the android_app->userData thing for?

2021-03-22 22:05 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
So, new stupid question: can't we just read the fd in base?

This gets rid of *all* this nonsense, since we basically just have to write to the fifo and call it a day.

Base just needs to read the fd when the ident is `fifo_id` (and no need for the extra wake either, the fact that data has been written means pollAll will detect it).

2021-03-22 22:10 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
yessssss. 
And therfore, to make the things easier in base I would like to turn the thing round in the struct. First the data and then the pointer. 
It should be freed on the end of the progam as we need the struct, the data and the pointer on every event!

2021-03-22 22:11 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
> I have allrdy done a kodev clean android and after that a kodev build android. Did not help.
> 
> Thank you.

`make dist-clean` is not `kodev clean`, it's better ;p.

2021-03-22 22:12 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
> yessssss.
> And therfore, to make the things easier in base I would like to turn the thing round in the struct. First the data and then the pointer.
> It should be freed on the end of the progam as we need the struct, the data and the pointer on every event!

c.f., my following answer, which should make *everything* even much simpler, if polling behaves sanely.

2021-03-22 22:19 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
In practice: Make the FIFO's addFd ident use a specific constant that we can retrieve from base, instead of the actual fd.

In base:

Actually store the outFd param:

```
 local outFd = ffi.new("int*[1]")
 local poll_state = android.lib.ALooper_pollAll(timeout, outFd, events, ffi.cast("void**", source))

 if poll_state >= 0 and poll_state == fifo_id, open & read on outFd[0]
```

2021-03-22 22:20 UTC, zwim commented
I don't think this works. Alooper is sitting there and does not end. The callback wakes it up. And only after that wake we can read the data. 
If we do that in the android part or the base part or the frontend part is no real gamechanger.
Logically it is an Android event so it should be decoded there?

Am 22. März 2021 23:06:01 MEZ schrieb NiLuJe ***@***.***>:
>@NiLuJe commented on this pull request.
>
>
>
>> @@ -215,18 +244,49 @@ static void* android_app_entry(void* param) {
>     android_app->inputPollSource.app = android_app;
>     android_app->inputPollSource.process = process_input;
> 
>-    ALooper* looper =
>ALooper_prepare(ALOOPER_PREPARE_ALLOW_NON_CALLBACKS);
>+    ALooper *looper =
>ALooper_prepare(ALOOPER_PREPARE_ALLOW_NON_CALLBACKS);
>+    native_glue_looper = looper;
>
>So, new stupid question: can't we just read the fd in base?
>
>This gets rid of *all* this nonsense, since we basically just have to
>write to the fifo and call it a day.
>
>Base just needs to read the fd when the ident is `fifo_id` (and no need
>for the extra wake either, the fact that data has been written means
>pollAll will detect it).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/koreader/android-luajit-launcher/pull/294#discussion_r599106543

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

2021-03-22 22:24 UTC, NiLuJe commented
But it should, this a wrapper around `poll`, the docs say:

```
ALOOPER_EVENT_INPUT | The file descriptor is available for read operations.
```

That's poll's `POLLIN`.

If you write to the FIFO, it'll be flagged POLLIN, that'll "wake" the poller.

2021-03-22 22:33 UTC, zwim commented on jni/android_native_app_glue/android_native_app_glue.c
> +    native_glue_looper = looper;
Ah that's a new quality :))) Very nice.
I will work on it the next days.

2021-03-23 19:51 UTC, NiLuJe commented
This might make what I was talking about earlier:

https://github.com/koreader/koreader-base/pull/1332/commits/7084a36a41e9042e5c55b30e626a4556bbd166e0

(Which means, yeah, the whole data pointer thing is completely bonkers and redundant, and we don't actually need it).

2021-03-23 20:59 UTC, NiLuJe commented
What looking at this revealed is that the CMD handling already functions in a similar manner, except it's using a pipe, not a named pipe.

Which makes sense: you don't actually need to access this outside of the process, so a simple anonymous pipe might make all the I/O and FS-related mess much clearer (c.f., msgread & msgwrite).

2021-03-23 21:32 UTC, NiLuJe commented
Ah. It's NDK code, so, who knows why the API design is weird and redundant ;o).

https://android.googlesource.com/platform/ndk/+/master/sources/android/native_app_glue
https://github.com/android/ndk-samples/blob/main/native-activity/app/src/main/cpp/main.cpp

2021-03-26 19:30 UTC, NiLuJe commented on assets/android.lua
> +};
There's already en enum w/ a list of `LOOPER_ID_` in `jni/android_native_app_glue/android_native_app_glue.h`, i'd add it there, > `LOOPER_ID_USER` ;).

2021-03-26 21:11 UTC, pazos commented on app/src/main/java/org/koreader/launcher/Device.kt
> +            val action = intent?.action
There's a idomatic way in kotlin of handling nullable vals. You can do:

```kotlin

intent?.let {
    when(it.action) {
    // here the cases
    }
}
```

you can also rename `it` to something you like more:

```kotlin

intent?.let { event ->
    when(event.action) { 
    // here the cases
    }
}
```

This way you can avoid NPE when evaluating with `when` :)

Not sure if is strictly neccesary here, but it is a good way of dealing with null types

2021-03-26 21:20 UTC, pazos commented on app/src/main/java/org/koreader/launcher/Device.kt
> +            Logger.e("Feed ALooper fifo: ERROR writing to  ALooper fifo: \"$MainApp.fifo_path\"")
A few nits:

1. You can avoid escaping the string with

```kotlin

"this is a string with a value inside. The value is ${MainApp.fifo_path}"
```

2. Please print the exception you catched or a stack trace (or both)
3. Not sure about the message body, sounds pretty arcane :/. In any case I would prefeer to use a proper tag and a message. Asumming the tag is `"Feed Alooper fifo"` and the message is `"error writing to file ${MainApp.fifo.path}: \n$e"`

You write: 
```kotlin
Logger.e("Feed Alooper fifo", "error writing to file ${MainApp.fifo.path}: \n$e")
```

All messages delivered by managed code (code that runs within the JVM) use a tag to differenciate them. Only the frontend code (and a few bits of very generic info) are used without a tag (they use the generic `KOReader` tag)

2021-03-26 21:21 UTC, pazos commented on app/src/main/java/org/koreader/launcher/MainActivity.kt
> +
please remove this one: very nit picky but you can add changes in a separate PR if you think is worth your time :)

2021-03-26 21:23 UTC, pazos commented on assets/android.lua
> +// for alooper.fifo messages
another nit:

Our own enums begin in https://github.com/koreader/android-luajit-launcher/blob/c53e6b2b29d8bb53e449e4994cf644ac1f99dcc8/assets/android.lua#L228

There're a few of them (for network, keycodes, screen timeout, haptic feedback ...) Please place them where you see it fits

2021-03-26 21:25 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +//        android_app->userData = message_to_lua;
please remove these comments

2021-03-26 21:27 UTC, NiLuJe commented
Friendly reminder that switching to a pipe will probably save you the trouble of dealing with the FS and paths ;).

> What looking at this revealed is that the CMD handling already functions in a similar manner, except it's using a pipe, not a named pipe.
> 
> Which makes sense: you don't actually need to access this outside of the process, so a simple anonymous pipe might make all the I/O and FS-related mess much clearer (c.f., msgread & msgwrite).

2021-03-26 21:31 UTC, pazos reviewed
Untested Ack. Looks very good and clean. A few very minor nits and it is ready for merging!!

I'm going to (ab)use this method for a few thingies. Namely: multiwindow state changes and apk download callbacks (ie: prompt to install the update when it is downloaded, like in other platforms)

But this method open a lot of doors: you can now write all kind of widgets and [shortcuts](https://developer.android.com/guide/topics/ui/shortcuts)

Very good work!!

2021-03-27 19:39 UTC, zwim commented
> Friendly reminder that switching to a pipe will probably save you the trouble of dealing with the FS and paths ;).
> 

> Friendly reminder that switching to a pipe will probably save you the trouble of dealing with the FS and paths ;).
> 
> > What looking at this revealed is that the CMD handling already functions in a similar manner, except it's using a pipe, not a named pipe.
> > Which makes sense: you don't actually need to access this outside of the process, so a simple anonymous pipe might make all the I/O and FS-related mess much clearer (c.f., msgread & msgwrite).

Thank you for the reminder. Unfortunately I think this is above my ability to implement. 

I don't see how/where I should create the pipe and how I can write to the pipe from `device.kt`. Where do I get the fd from?

2021-03-27 19:51 UTC, NiLuJe commented
On the C side: You create it basically the same place you currently use `mkfifo`, you can store both ends of the pipe in the giant struct like CMD does for `msgwrite`/`msgread`.

On the Lua side: it's returned by ALooper in the fd pointer.

2021-03-27 19:55 UTC, zwim commented
C and LUA side seems clear, but I need the filedescriptor of the pipe in kotlin (Device.kt), so that I can write the messages there. Kotlin is my problem.

2021-03-27 21:16 UTC, NiLuJe commented
Ah, that may be a good point. I have zero clue about Java/Kotlin, so I completely ignored this aspect of the equation ;p.

If you don't have access to the `android_app` object from there (we do in Lua, so I assumed we did in Java, but, again: no clue ^^), then, yeah, the file handle avoids that issue.

2021-03-27 23:54 UTC, pazos commented on app/src/main/java/org/koreader/launcher/Device.kt
> +            Logger.e("Feed ALooper fifo:", "ERROR writing to file: ${MainApp.fifo_path}: \n$e")
```suggestion
            Logger.e("FIFO", "Cannot write to file ${MainApp.fifo_path}: \n$e")
```

2021-03-27 23:55 UTC, pazos commented on app/src/main/java/org/koreader/launcher/Device.kt
> +            Logger.e("Feed ALooper fifo:", "ERROR writing to file: ${MainApp.fifo_path}: \n$e")
As it is already logged as an ERROR in logcat :p

2021-03-27 23:57 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +            LOGV("%s: FIFO \"%s\" already exists", TAG, fifo_file);
```suggestion
            LOGV("%s: file %s already exists", TAG, fifo_file);
```

2021-03-27 23:57 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +            LOGE("%s: FIFO \"%s\" cannot be created!", TAG, fifo_file);
```suggestion
            LOGE("%s: file %s cannot be created!", TAG, fifo_file);
```

2021-03-27 23:58 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +        LOGV("%s: FIFO \"%s\" created", TAG, fifo_file);
```suggestion
        LOGV("%s: file %s created", TAG, fifo_file);
```

2021-03-28 00:25 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +    // create and open fifo for communication with MainActivity
```suggestion
    */ from https://github.com/koreader/android-luajit-launcher/pull/294

    We use a named pipe to push events to our main loop running in LuaJIT.
    Here we create the file, open it and register it as a poll source if everything went well.
    
    Its state is available as part of the android ffi module
*/
```

2021-03-28 00:26 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +    // create and open fifo for communication with MainActivity
or something as verbose as that :)

2021-03-28 00:33 UTC, pazos commented on assets/android.lua
> +    EVENT_POWER_CONNECTED = 100,
A little nit I forgot.

Please use AEVENT instead of EVENT. Android uses that in their native activity API and we use that too in our own glue code

`AHAPTIC*`, `ASCREEN*` ...

Maybe there're better ways of calling the part we implement on our own but should be consistent and in other PR :)

2021-03-28 00:37 UTC, pazos approved these changes
Final round of nits. Looks almost ready to me, @NiLuJe @zwim

2021-03-28 00:51 UTC, pazos commented
One question that I missed on the review: what happens when a system broadcast event happens and the app is running in the background? Is the event received by the kotlin side?. 

I'm pretty sure our own lua loop is running from `onCreate` to `onDestroy` and we're able to consume relayed events when the app is not focused but I'm not sure how broadcast receivers work when they're part of an activity

2021-03-28 00:59 UTC, NiLuJe commented
Nothing to add on the C/Lua front, thanks for bearing with me and my wild ideas ;).

2021-03-28 01:01 UTC, NiLuJe commented on app/src/main/java/org/koreader/launcher/Device.kt
> +    // post an 32 bit message which can be evaluated after an ALooper_pollAll()
Stupid grammar nit:
```suggestion
    // post a 32-bit message which can be evaluated after an ALooper_pollAll()
```

2021-03-28 01:01 UTC, NiLuJe commented on app/src/main/java/org/koreader/launcher/Device.kt
> +        // 32bit (4-byte) get transmitted. The low byte is the command
```suggestion
// 32 bits (4 bytes) get transmitted. The low byte is the command.
```

2021-03-28 07:57 UTC, zwim commented
> One question that I missed on the review: what happens when a system broadcast event happens and the app is running in the background? Is the event received by the kotlin side?.
> 
> I'm pretty sure our own lua loop is running from `onCreate` to `onDestroy` and we're able to consume relayed events when the app is not focused but I'm not sure how broadcast receivers work when they're part of an activity

On my phone: 
I start KOReader connected to power -> I CAN see the charging symbol in the status line.
KOReader to background, playing with some apps.
Unplugging the phone.
Switch to KOReader -> I CAN'T see the charging symbol in the status line.

So I think the mechanism works in background too.

2021-03-30 21:27 UTC, pazos commented on jni/android_native_app_glue/android_native_app_glue.c
> +        LOGV("%s: FIFO \"%s\" created", TAG, fifo_file);
@zwim: this one too, please. And it's ready to be merged :)

2021-03-31 15:23 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    snprintf(fifo_file, sizeof(fifo_file), "%s/%s", fifo_path, FIFO_NAME);
Didn't we conclude that `sizeof` on a VLA was a bad idea?

2021-03-31 15:26 UTC, NiLuJe commented on jni/android_native_app_glue/android_native_app_glue.c
> +    snprintf(fifo_file, sizeof(fifo_file), "%s/%s", fifo_path, FIFO_NAME);
I'm genuinely curious what this does. It's *conceivable* that the compiler groks what happens and actually does

```C
size_t len = strlen(fifo_path) + strlen(FIFO_NAME) + 2U;
char fifo_file[len];
snprintf(fifo_file, len, "%s/%s", fifo_path, FIFO_NAME);
```

But I'd probably be more confident in making that explicit ;).

2021-04-01 12:02 UTC, merged