Add support for C64P
koreader/android-luajit-launcher pull request #474
Opened 2024-04-05 01:40 UTC by ovehbe

2024-04-05 21:23 UTC, Frenzie approved these changes

2024-04-05 22:49 UTC, pazos requested changes
thanks for the patch, @ovehbe!

 A few changes required:

- A better name for the device
- Remove the device from LightsDevice, since you're not using it.

You can get the idea from https://github.com/koreader/android-luajit-launcher/pull/475, which is exactly yours with these little changes :)

2024-04-06 12:39 UTC, hugleo commented on app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt
> +        BOYUE_C64P,
remove

2024-04-06 12:39 UTC, hugleo commented on app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
> +                DeviceInfo.EinkDevice.BOYUE_C64P,
I would prefer add to RK3368 driver since you got more recent device. My test apk was RK3368. But it's OK if both works. for you.

2024-04-06 22:40 UTC, ovehbe commented on app/src/main/java/org/koreader/launcher/device/EPDFactory.kt
> +                DeviceInfo.EinkDevice.BOYUE_C64P,
Got it, I'll modify accordingly.

2024-04-06 23:01 UTC, hugleo approved these changes

2024-04-07 00:16 UTC, pazos approved these changes
thanks! lgtm

2024-04-07 00:17 UTC, merged